---
title: "Class 03/05/2020"
author: "Mak Famulari"
date: "March 5, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(googlesheets4)
library(janitor)
library(tidyverse)
library(moderndive)
library(infer)
sheets_deauth()
# There is nothing wrong with reading in, and cleaning up, your data in the
# setup R code chunk. But, to be honest, I am just doing this here because I
# couldn't figure out how to turn off the message from read_sheet.

x <- read_sheet(ss =  "14HmwN2cEVAJHupuehCuLdwG9BXtR3COrxDgaaylLhkA") %>% 
  clean_names() %>% 
  mutate(percent_red = red / (red + white))
```

```{r}
# I don't really like this plot. There are only 26 allowed values, from 0% to
# 100% in increments of 4%. So, I should be able to see separate points. But I
# could never get that to work, even using geom_bar() and other tricks. 
# Ahh. Now I look at the data and see that there are several impossible (?)
# points: 8.7%, 19%, 25% and 77%. Is that bad data?

x %>% 
  ggplot(aes(percent_red)) +
    geom_histogram(bins = 20) +
    labs(title = "Percentage of Red Beads Drawn",
        subtitle = "Should we be suspicious of those outliers?",
        caption = "Classroom data from 2020-03-03",
        x = "Percentage of Red Beads Out of 25 Drawn",
        y = "Count") 
```

```{r}
urn <- tibble(bean_ID = 1:10000,
              color = c(rep("Red", 2000), rep("White", 8000)))
```

```{r}
urn %>% 
  rep_sample_n(size = 25, reps = 1) %>% 
  summarize(red_sum = sum(color == "Red")) %>% 
  mutate(perc_red = red_sum / 25)

y <- urn %>% 
  rep_sample_n(size = 25, reps = 51) %>% 
  group_by(replicate) %>% 
  summarize(red_sum = sum(color == "Red")) %>% 
  mutate(perc_red = red_sum / 25)

simulate_class <- function(urn) {
  urn %>% 
  rep_sample_n(size = 25, reps = 51) %>% 
  group_by(replicate) %>% 
  summarize(red_sum = sum(color == "Red")) %>% 
  mutate(perc_red = red_sum / 25)
}

sim_results <- tibble(sim_ID = 1:3, 
                 results = map(sim_ID, ~ simulate_class(urn)))

ggplot(y, aes(x = perc_red)) +
  geom_histogram(bins = 20, binwidth = 0.05, boundary = 0.4, color = "white") +
  labs(x = "Proportion of 25 balls that were red", 
       title = "Distribution of 51 proportions red") 

sim_results[[2]][[2]] %>% 
  ggplot(aes(perc_red)) +
  geom_histogram(bins = 20)

```
